### ISSUE TITLE
How to connect UART?

### ISSUE THREAD

**Issue by sapzxc** [Xinyuan-LilyGO/T-Internet-COM#1]
Hi!

Does it possible to connect UART, especially to work with modbus protocol?

 I looking something with full network support (wifi, LAN, BLE, GSM/sim-card) and possible to to work with cheap modbus modules. Main goal is maximum online stability to send statistics to the internet and local control via bluetooth.

**Comment by LilyGO** [comment]
Most of the chip pins are already occupied, and there are only SD card pins with download pins that can be used with UART
