### ISSUE TITLE
documentation / source code of stock firmware

### ISSUE THREAD

**Issue by beta-tester** [Xinyuan-LilyGO/T-Internet-COM#15]
hi,
where to find the documentation and source code of the stock firmware of the T-Internet-COM module?

**Comment by mmMicky** [comment]
https://github.com/Xinyuan-LilyGO/T-Internet-COM/tree/main/example
There are basics here is how to use.

**Comment by beta-tester** [comment]
from what i saw on the serial output and the example codes, the stock firmware is:
[FactoryTest](https://github.com/Xinyuan-LilyGO/T-Internet-COM/tree/main/example/PlatformIO/FactoryTest)

i thought it is more than just a test firmware.
ok, then i can overwrite that firmware with my with no risk.

thank you.
