### ISSUE TITLE
what is the AUX antenna connector for?

### ISSUE THREAD

**Issue by beta-tester** [Xinyuan-LilyGO/T-Internet-COM#16]
hi,

on a PCIE-SIM7600x module there are GNSS, MAIN and AUX connectors.
GNSS and MAIN i know what it is good for, but what is AUX?

**Comment by mmMicky** [comment]
auxiliary antenna. Used to assist LTE or 2G signal acquisition.

**Comment by beta-tester** [comment]
you mean as secondary LTE antenna?

i found a manual of all AT commands of the SIM7600 module and it looks like it has its own WiFi & BT built in.
i thought AUX is maybe an antenna connector for that Wifi & BT of  the SIM7600 module, beside the WiFi & BT of the ESP32 module.

**Comment by mmMicky** [comment]
for example. Regardless of sim800L or other signals, it will have an AUX interface. And SIM800L does not have WIFI function.

**Comment by beta-tester** [comment]
that's strange.
why does SIMCOM list AT commands for WIFI and BT in their SIM7600 manual (SIM7500_SIM7600 Series_AT Command Manual_V3.00.pdf),
but the SIM7600 module itself does not have WIFI/BT functioallity (SIM7600 Series_SPEC_202111.pdf).
~~or does that SIM7600 module support WIFI/BT over its USB-OTG?~~
(i read the harware design guids (SIM7600_PCIEMIFI_Hardware_Design_V1.01(221103).pdf) - WIFI, can be archived with a specific module version but needs additional hardware)
for others like me who has those questions about the AUX connector...
![SIM7600Module block diagram](https://user-images.githubusercontent.com/4750719/219296088-91121d17-f2ce-438d-bbe8-5c73fea070e4.png)

SIM7600_PCIEMIFI_Hardware_Design_V1.01(221103).pdf
![SIM7600_MIFI](https://user-images.githubusercontent.com/4750719/219297706-b286be56-c6af-4300-bc96-eb3daeefa00a.png)

**Comment by beta-tester** [comment]
on the T-Internet-COM module there are the V_BUS, D+, D-, GND lines of the SIM7600 module populated as test pads.
in the schematics it looka V_BUS on the PCIE-Module goes to V_MAIN (+4V) and on the T_Internet-COM module V_BUS goes to the USB-C connector (+5V).

i will not destroy anything...
how can i connect the V_BUS, D+, D-, GND test pads correctly to hook up PCIE-SIM7600 to a PC to DEBUG the module, upload SIM7600-Firmware, use its RNDIS functionallity?

sorry when my questions are stupid - i try to understand the PCIE-SIM7600 module and its capabilities
