### ISSUE TITLE
Cannot get SIM7600G to register on network

### ISSUE THREAD

**Issue by claudepio** [Xinyuan-LilyGO/T-Internet-COM#4]
Running TinyGSM_Allfunctions, The SIM card is recognized, but device cannot register on network.
I use the same device on a T-PCIE v1.1 and it works fine.

Claude

**Comment by LilyGO** [comment]
https://github.com/Xinyuan-LilyGO/T-Internet-COM/tree/main/example/ESP-IDF/pppoe2ap

It is recommended to restart a few times to test whether the registration can be normal. I also noticed that it is not 100% successful, and I am now looking for the reason. I hope it can help you.

**Comment by LilyGO** [comment]
The problem is too long, you can open it again if necessary
