### ISSUE TITLE
WiFi-AP function forwarding over Lte

### ISSUE THREAD

**Issue by etempm** [Xinyuan-LilyGO/T-Internet-COM#5]
Hi, I can not find example about WiFi-AP function forwarding over 4g lte modem (sim7600a).

I have some sensors and camera works over wifi to send data to webservice over internet.

 This is urgent for a project. Can you share example about this?

**Comment by LilyGO** [comment]
https://github.com/Xinyuan-LilyGO/T-Internet-COM/tree/main/example/ESP-IDF/pppoe2ap

**Comment by sanjulanipun** [comment]
> https://github.com/Xinyuan-LilyGO/T-Internet-COM/tree/main/example/ESP-IDF/pppoe2ap

Hi im working with this board, i need to know can we run it arduino ide, because i need to run that code with my own some funtions. It have arduino custom made special library it only work with arduino ide. Are you possible help me for that.

I just only need your funtion get into arduino ide.

**Comment by LilyGO** [comment]
ESP32 also uses IDF in the bottom layer of Arduino. You can import entire component projects into your library.

**Comment by LilyGO** [comment]
The problem is too long, you can open it again if necessary
