### ISSUE TITLE
possible to make "eth2ap" code into arduino ide code?

### ISSUE THREAD

**Issue by sanjulanipun** [Xinyuan-LilyGO/T-Internet-COM#6]
**eth2ap** example code is working on esp idf. so i need to make it with the same thing using Arduino ide. Is it possible to do?

**Comment by LilyGO** [comment]
https://github.com/espressif/esp-gateway

There is no plan to add the depth function to Arduino in a short period of time. If you need to integrate it into Arduino, it is recommended that you refer to this connection. The bottom layer of Arduino also uses IDF. You can extract and modify part of the code to run on Arduino.
