### ISSUE TITLE
ESP-IDF "eth2ap" this example after build and upload Board is restarting

### ISSUE THREAD

**Issue by sanjulanipun** [Xinyuan-LilyGO/T-Internet-COM#7]
hi i run ESP-IDF "eth2ap" and it builds secussfully. i not make any modifications and flash it into board. after flash done board is getting restarting continuously.  i attach deceive monitor outputs, Does anyone know why it happening?

1.
![A](https://user-images.githubusercontent.com/32708235/162880599-9b21e89b-9ae3-4fab-b897-c47e52eb60f2.PNG)
2.
![B](https://user-images.githubusercontent.com/32708235/162880606-420bcc40-7d57-4254-b30c-9c6e2855a70b.PNG)
3.
![C](https://user-images.githubusercontent.com/32708235/162880615-928877e9-522e-4938-9663-2670d286dcf0.PNG)

**Comment by LilyGO** [comment]
https://github.com/espressif/esp-gateway
It is recommended that you refer to this connection, you only need to simply modify some PIN pins to successfully drive
